apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-cluster
  namespace: rook-ceph
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
  values:
    cephClusterSpec:
      storage:
        useAllNodes: true
        deviceFilter: "^nvme\\d+n\\d+$"
      placement:
        all:
          tolerations:
            - effect: NoSchedule
              key: node-role.kubernetes.io/control-plane
              operator: Exists