apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ceph-cluster
  namespace: flux-system
spec:
  interval: 1h
  dependsOn: 
  - name: rook-ceph
  path: ./kubernetes/infrastructure/ceph-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system